copy_capsule_static_resources <- function(source_dir, appdir) {
  if (!dir.exists(source_dir)) {
    return(invisible(FALSE))
  }

  copy_dir <- function(from, to) {
    if (!dir.exists(from)) {
      return(invisible(FALSE))
    }

    dir.create(to, recursive = TRUE, showWarnings = FALSE)

    files <- list.files(
      from,
      all.files = TRUE,
      no.. = TRUE,
      full.names = TRUE
    )

    if (length(files) > 0) {
      file.copy(
        from = files,
        to = to,
        recursive = TRUE,
        overwrite = TRUE
      )
    }

    invisible(TRUE)
  }

  copy_dir(
    from = file.path(source_dir, "pdf"),
    to = file.path(appdir, "www", "pdf")
  )

  copy_dir(
    from = file.path(source_dir, "img"),
    to = file.path(appdir, "www", "img")
  )

  copy_dir(
    from = file.path(source_dir, "www"),
    to = file.path(appdir, "www")
  )

  copy_dir(
    from = file.path(source_dir, "data"),
    to = file.path(appdir, "data")
  )

  invisible(TRUE)
}

write_standalone_board_helpers <- function(file) {
  helper_functions <- c(
    "serious_board_step_ids",
    "serious_board_get_step",
    "serious_board_step_status",
    "serious_board_status_icon",
    "serious_board_status_label",
    "serious_board_status_border_color",
    "serious_board_section_id",
    "serious_board_default_section_colors",
    "serious_board_section_color",
    "serious_board_get_position",
    "serious_board_make_nodes",
    "serious_board_make_edges",
    "serious_board_widget"
  )

  ns <- environment(write_standalone_board_helpers)

  missing_functions <- helper_functions[
    !vapply(
      helper_functions,
      exists,
      logical(1),
      envir = ns,
      inherits = FALSE
    )
  ]

  if (length(missing_functions) > 0) {
    stop(
      "Cannot generate standalone board helpers. Missing functions: ",
      paste(missing_functions, collapse = ", "),
      call. = FALSE
    )
  }

  tmp <- tempfile(fileext = ".R")

  dump(
    list = helper_functions,
    file = tmp,
    envir = ns
  )

  lines <- readLines(tmp, warn = FALSE)

  writeLines(
    c(
      "# Standalone SeRiouS board helpers",
      "# Generated by write_capsule_app(). Do not edit by hand.",
      "",
      "`%||%` <- function(x, y) {",
      "  if (is.null(x)) y else x",
      "}",
      "",
      lines
    ),
    con = file
  )

  invisible(file)
}

write_standalone_ui_helpers <- function(file) {
  helper_functions <- c(
    "serious_ui_css",
    "serious_header_ui",
    "serious_step_card_class",
    "serious_badge_class"
  )

  ns <- environment(write_standalone_ui_helpers)

  missing_functions <- helper_functions[
    !vapply(
      helper_functions,
      exists,
      logical(1),
      envir = ns,
      inherits = FALSE
    )
  ]

  if (length(missing_functions) > 0) {
    stop(
      "Cannot generate standalone UI helpers. Missing functions: ",
      paste(missing_functions, collapse = ", "),
      call. = FALSE
    )
  }

  tmp <- tempfile(fileext = ".R")

  dump(
    list = helper_functions,
    file = tmp,
    envir = ns
  )

  lines <- readLines(tmp, warn = FALSE)

  writeLines(
    c(
      "# Standalone SeRiouS UI helpers",
      "# Generated by write_capsule_app(). Do not edit by hand.",
      "",
      "`%||%` <- function(x, y) {",
      "  if (is.null(x)) y else x",
      "}",
      "",
      lines
    ),
    con = file
  )

  invisible(file)
}

#' Write a SeRiouS capsule as a Shiny application
#'
#' @param capsule A `"learning_capsule"` object or the id of a registered capsule.
#' @param appdir Directory where the Shiny application should be written.
#' @param overwrite Logical. If `TRUE`, an existing directory may be overwritten.
#' @param standalone Logical. If `TRUE`, writes a standalone app that does not
#'   depend on the SeRiouS package at runtime.
#'
#' @return Invisibly returns the normalized application directory.
#' @export
write_capsule_app <- function(capsule,
                              appdir,
                              overwrite = FALSE,
                              standalone = FALSE) {
  if (!is.character(appdir) || length(appdir) != 1 || !nzchar(appdir)) {
    stop("'appdir' must be a single non-empty character string.", call. = FALSE)
  }

  if (!is.logical(overwrite) || length(overwrite) != 1) {
    stop("'overwrite' must be TRUE or FALSE.", call. = FALSE)
  }

  if (!is.logical(standalone) || length(standalone) != 1) {
    stop("'standalone' must be TRUE or FALSE.", call. = FALSE)
  }

  if (is.character(capsule) && length(capsule) == 1) {
    capsule <- get_capsule(capsule)
  }

  if (!inherits(capsule, "learning_capsule")) {
    stop(
      "'capsule' must be a learning_capsule object or a registered capsule id.",
      call. = FALSE
    )
  }

  validate_capsule(
    capsule,
    parse_code = FALSE,
    check_packages = FALSE,
    verbose = FALSE
  )

  source_dir <- NULL

  if (!is.null(capsule$resources) &&
      !is.null(capsule$resources$capsule_dir)) {
    source_dir <- normalizePath(capsule$resources$capsule_dir, mustWork = TRUE)
  }

  appdir_norm <- normalizePath(appdir, mustWork = FALSE)

  if (!is.null(source_dir) && identical(appdir_norm, source_dir)) {
    stop(
      "'appdir' cannot be the source capsule directory. ",
      "Choose a separate output directory.",
      call. = FALSE
    )
  }

  if (dir.exists(appdir)) {
    existing_files <- list.files(appdir, all.files = TRUE, no.. = TRUE)

    if (length(existing_files) > 0 && !isTRUE(overwrite)) {
      stop(
        "'appdir' already exists and is not empty. ",
        "Use overwrite = TRUE or choose another directory.",
        call. = FALSE
      )
    }

    if (isTRUE(overwrite)) {
      unlink(appdir, recursive = TRUE, force = TRUE)
    }
  }

  dir.create(appdir, recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(appdir, "www"), recursive = TRUE, showWarnings = FALSE)

  if (!is.null(source_dir)) {
    copy_capsule_static_resources(
      source_dir = source_dir,
      appdir = appdir
    )
  }

  capsule_file <- file.path(appdir, "capsule.rds")
  saveRDS(capsule, capsule_file)

  app_file <- file.path(appdir, "app.R")

  capsule_packages <- unique(c("shiny", capsule$packages %||% character()))
  capsule_packages <- setdiff(capsule_packages, c("SeRiouS", "base"))

  if (isTRUE(standalone)) {
    capsule_packages <- unique(c(
      "shiny",
      "visNetwork",
      capsule$packages %||% character()
    ))

    capsule_packages <- setdiff(capsule_packages, c("SeRiouS", "base"))
  }

  library_lines <- sprintf(
    "suppressPackageStartupMessages(library(%s))",
    capsule_packages
  )

  if (isTRUE(standalone)) {
    engine_source <- system.file(
      "standalone",
      "serious_engine_standalone.R",
      package = "SeRiouS"
    )

    if (!nzchar(engine_source) || !file.exists(engine_source)) {
      stop(
        "Standalone engine file not found. ",
        "Expected inst/standalone/serious_engine_standalone.R.",
        call. = FALSE
      )
    }

    file.copy(
      from = engine_source,
      to = file.path(appdir, "serious_engine_standalone.R"),
      overwrite = TRUE
    )

    write_standalone_board_helpers(
      file = file.path(appdir, "serious_board_helpers.R")
    )

    write_standalone_ui_helpers(
      file = file.path(appdir, "serious_ui_helpers.R")
    )

    writeLines(
      c(
        library_lines,
        "",
        "source(\"serious_board_helpers.R\")",
        "source(\"serious_ui_helpers.R\")",
        "source(\"serious_engine_standalone.R\")",
        "",
        "capsule <- readRDS(\"capsule.rds\")",
        "",
        "run_capsule_standalone(capsule)"
      ),
      app_file
    )
  } else {
    writeLines(
      c(
        "suppressPackageStartupMessages(library(shiny))",
        "suppressPackageStartupMessages(library(SeRiouS))",
        "",
        "capsule <- readRDS(\"capsule.rds\")",
        "",
        "SeRiouS::run_learning_capsule(capsule)"
      ),
      app_file
    )
  }

  readme_file <- file.path(appdir, "README.md")

  writeLines(
    c(
      paste0("# ", capsule$title),
      "",
      "This folder contains a Shiny application generated by SeRiouS.",
      "",
      "## Run locally",
      "",
      "```r",
      "shiny::runApp(\".\")",
      "```",
      "",
      "## Contents",
      "",
      "- `app.R`: Shiny entry point.",
      "- `capsule.rds`: serialized SeRiouS capsule.",
      "- `www/`: static web resources.",
      if (isTRUE(standalone)) {
        "- `serious_engine_standalone.R`: standalone SeRiouS runtime."
      } else {
        "- This app depends on the installed SeRiouS package."
      }
    ),
    readme_file
  )

  invisible(normalizePath(appdir, mustWork = TRUE))
}


#' Export a SeRiouS capsule as a shinylive application
#'
#' @param capsule A `"learning_capsule"` object or the id of a registered capsule.
#' @param destdir Directory where the shinylive application should be exported.
#' @param appdir Optional temporary Shiny application directory. If `NULL`, a
#'   temporary directory is created.
#' @param overwrite Logical. If `TRUE`, an existing export directory may be
#'   overwritten.
#' @param repos WebAssembly package repository used by shinylive.
#' @param keep_appdir Logical. If `TRUE`, keeps the intermediate Shiny app
#'   directory.
#' @param standalone Logical. If `TRUE`, exports a standalone app that does not
#'   depend on the SeRiouS package at runtime.
#' @param ... Additional arguments passed to `shinylive::export()`.
#'
#' @return Invisibly returns the normalized export directory.
#' @export
export_capsule_shinylive <- function(capsule,
                                     destdir,
                                     appdir = NULL,
                                     overwrite = FALSE,
                                     repos = "https://repo.r-wasm.org/",
                                     keep_appdir = FALSE,
                                     standalone = TRUE,
                                     ...) {
  if (!requireNamespace("shinylive", quietly = TRUE)) {
    stop(
      "Package 'shinylive' is required to export a capsule. ",
      "Install it with install.packages('shinylive').",
      call. = FALSE
    )
  }

  if (!is.character(destdir) || length(destdir) != 1 || !nzchar(destdir)) {
    stop("'destdir' must be a single non-empty character string.", call. = FALSE)
  }

  if (!is.logical(overwrite) || length(overwrite) != 1) {
    stop("'overwrite' must be TRUE or FALSE.", call. = FALSE)
  }

  if (!is.logical(keep_appdir) || length(keep_appdir) != 1) {
    stop("'keep_appdir' must be TRUE or FALSE.", call. = FALSE)
  }

  if (!is.logical(standalone) || length(standalone) != 1) {
    stop("'standalone' must be TRUE or FALSE.", call. = FALSE)
  }

  created_appdir <- is.null(appdir)

  if (created_appdir) {
    appdir <- tempfile("serious-shiny-app-")
  }

  if (!is.character(appdir) || length(appdir) != 1 || !nzchar(appdir)) {
    stop("'appdir' must be NULL or a single non-empty character string.", call. = FALSE)
  }

  if (created_appdir && !isTRUE(keep_appdir)) {
    on.exit(unlink(appdir, recursive = TRUE, force = TRUE), add = TRUE)
  }

  if (dir.exists(destdir)) {
    existing_files <- list.files(destdir, all.files = TRUE, no.. = TRUE)

    if (length(existing_files) > 0 && !isTRUE(overwrite)) {
      stop(
        "'destdir' already exists and is not empty. ",
        "Use overwrite = TRUE or choose another directory.",
        call. = FALSE
      )
    }

    if (isTRUE(overwrite)) {
      unlink(destdir, recursive = TRUE, force = TRUE)
    }
  }

  write_capsule_app(
    capsule = capsule,
    appdir = appdir,
    overwrite = TRUE,
    standalone = standalone
  )

  shinylive::export(
    appdir = appdir,
    destdir = destdir,
    repos = repos,
    ...
  )

  invisible(normalizePath(destdir, mustWork = TRUE))
}
